"""Semantic categorization, graph discovery, synthesis, caching, and export."""

from chatgpt_archive_compiler.semantic.errors import SemanticAtlasError
from chatgpt_archive_compiler.semantic.graph import (
    build_similarity_graph,
    discover_communities,
)
from chatgpt_archive_compiler.semantic.local_providers import (
    LocalHashingEmbeddingProvider,
    LocalHeuristicAnalysisProvider,
)
from chatgpt_archive_compiler.semantic.models import (
    ArchiveSynthesis,
    ArchiveSynthesisBundle,
    ArchiveSynthesisRequest,
    Category,
    CategoryAssignment,
    CategoryDraft,
    CategoryInterpretation,
    CategoryProfile,
    ConversationAnalysis,
    ConversationReference,
    ConversationRepresentation,
    EmbeddingRecord,
    GraphEdge,
    GraphSummary,
    ProjectTimeline,
    ReviewCode,
    ReviewItem,
    ReviewPriority,
    ReviewQueue,
    SemanticAtlas,
    SemanticAtlasManifest,
    SemanticAtlasOptions,
    SemanticAtlasResult,
    SemanticRunEstimate,
    Taxonomy,
    TaxonomyInterpretation,
    TaxonomyInterpretationRequest,
    TimelineEvent,
)
from chatgpt_archive_compiler.semantic.openai_provider import (
    OpenAIEmbeddingProvider,
    OpenAIStructuredAnalysisProvider,
)
from chatgpt_archive_compiler.semantic.pipeline import (
    SemanticProgressCallback,
    build_semantic_atlas,
    conversation_key_for,
    estimate_semantic_run,
    prepare_conversation_representations,
)
from chatgpt_archive_compiler.semantic.providers import (
    EmbeddingProvider,
    StructuredAnalysisProvider,
)

__all__ = [
    "ArchiveSynthesis",
    "ArchiveSynthesisBundle",
    "ArchiveSynthesisRequest",
    "Category",
    "CategoryAssignment",
    "CategoryDraft",
    "CategoryInterpretation",
    "CategoryProfile",
    "ConversationAnalysis",
    "ConversationReference",
    "ConversationRepresentation",
    "EmbeddingProvider",
    "EmbeddingRecord",
    "GraphEdge",
    "GraphSummary",
    "LocalHashingEmbeddingProvider",
    "LocalHeuristicAnalysisProvider",
    "OpenAIEmbeddingProvider",
    "OpenAIStructuredAnalysisProvider",
    "ProjectTimeline",
    "ReviewCode",
    "ReviewItem",
    "ReviewPriority",
    "ReviewQueue",
    "SemanticAtlas",
    "SemanticAtlasError",
    "SemanticAtlasManifest",
    "SemanticAtlasOptions",
    "SemanticAtlasResult",
    "SemanticRunEstimate",
    "SemanticProgressCallback",
    "StructuredAnalysisProvider",
    "Taxonomy",
    "TaxonomyInterpretation",
    "TaxonomyInterpretationRequest",
    "TimelineEvent",
    "build_semantic_atlas",
    "build_similarity_graph",
    "conversation_key_for",
    "discover_communities",
    "estimate_semantic_run",
    "prepare_conversation_representations",
]
